site_name: ComfyTweaker Documentation
theme:
  name: material
  features:
    - content.code.copy


plugins:
  - search
  - mkdocstrings

watch:
  - ../src

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tweak Files Reference: reference/tweak_files.md
  - Errata: errata.md
